import { RevenueIngestForm } from "@/components/revenue-ingest-form";
import { requireAppContext } from "@/lib/auth/context";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export default async function RevenueOsPage() {
  const context = await requireAppContext(); const admin = createSupabaseAdminClient();
  if (!admin) return <p className="form-alert">Revenue intelligence persistence is unavailable.</p>;
  const [{ data: calls }, { data: assets }, { data: entities }] = await Promise.all([
    admin.from("revenue_calls").select("id,title,account_name,status,created_at").eq("organization_id", context.organization.id).order("created_at", { ascending: false }).limit(10),
    admin.from("revenue_assets").select("id,title,asset_type,department,status,evidence_coverage,updated_at").eq("organization_id", context.organization.id).order("updated_at", { ascending: false }).limit(40),
    admin.from("knowledge_entities").select("id,entity_type,canonical_label,evidence_count,distinct_call_count,confidence,status").eq("organization_id", context.organization.id).order("updated_at", { ascending: false }).limit(20),
  ]);
  return <><header className="page-header"><div><span className="eyebrow">Canonical Revenue OS</span><h1>One call in. Governed intelligence out.</h1><p className="page-lead">A single evidence ledger powers personas, practice, content, coaching, and cross-department assets.</p></div></header><RevenueIngestForm /><section className="metric-grid mt-6"><article className="metric-card"><div><span>Calls ingested</span><strong>{calls?.length ?? 0}</strong><small>Consent-bound sources</small></div></article><article className="metric-card"><div><span>Assets planned</span><strong>{assets?.length ?? 0}</strong><small>Review before publication</small></div></article><article className="metric-card"><div><span>Knowledge entities</span><strong>{entities?.length ?? 0}</strong><small>Evidence-connected</small></div></article><article className="metric-card"><div><span>Approved assets</span><strong>{assets?.filter((asset) => asset.status === "approved" || asset.status === "published").length ?? 0}</strong><small>Activated knowledge</small></div></article></section><div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="card"><h2 className="font-semibold">Asset factory</h2><div className="mt-4 space-y-3">{(assets ?? []).length ? assets!.map((asset) => <article className="rounded-xl border border-slate-200 p-3" key={asset.id}><div className="flex justify-between gap-3"><strong className="text-sm">{asset.title}</strong><span className="badge">{asset.status}</span></div><p className="mt-1 text-xs text-slate-500">{asset.department} · {Math.round(Number(asset.evidence_coverage) * 100)}% evidence coverage</p></article>) : <p className="text-sm text-slate-500">Ingest a transcript to plan the 20 governed asset types.</p>}</div></section><section className="card"><h2 className="font-semibold">Living knowledge graph</h2><div className="mt-4 space-y-3">{(entities ?? []).length ? entities!.map((entity) => <article className="rounded-xl border border-slate-200 p-3" key={entity.id}><div className="flex justify-between gap-3"><strong className="text-sm">{entity.canonical_label}</strong><span className="badge">{entity.entity_type}</span></div><p className="mt-1 text-xs text-slate-500">{entity.evidence_count} observations · {entity.distinct_call_count} calls · {Math.round(Number(entity.confidence) * 100)}% confidence</p></article>) : <p className="text-sm text-slate-500">Approved and candidate customer evidence will appear here.</p>}</div></section></div></>;
}
